

const P=JSON.parse(document.getElementById('payload').textContent),plot=document.getElementById('plot'),F=P.time.length;
const RED='#d62728',BLUE='#1f77b4',DEFAULT_CAMERA={eye:{x:1.5,y:-1.7,z:1.1},up:{x:0,y:0,z:1}},traces=[];
let playing=false,logicalFrame=0,renderedFrame=-1,playAnchorFrame=0,playAnchorWallTime=0,speed=1;
let cameraInteracting=false,renderBusy=false,renderPending=false,dynamicHidden=false,hidePending=false,wheelEndTimer=null;
const redTraj=[],blueTraj=[]; for(let a=0;a<4;a++){redTraj.push(traces.length);traces.push({type:'scatter3d',mode:'lines',name:`Red R${a+1}`,x:[],y:[],z:[],line:{color:RED,width:3}})}
for(let w=0;w<P.blue[0].length;w++)for(let a=0;a<4;a++){blueTraj.push(traces.length);traces.push({type:'scatter3d',mode:'lines',name:`Blue W${w+1} B${a+1}`,x:[],y:[],z:[],line:{color:BLUE,width:2,dash:['solid','dash','dot'][w%3]}})}
const redCurrent=traces.length;traces.push({type:'scatter3d',mode:'markers+text',name:'Current Red',x:[],y:[],z:[],text:[],customdata:[],marker:{size:6,color:RED},hovertemplate:'%{customdata[0]}<br>Side: Red<br>X: %{x:.1f} m<br>Y: %{y:.1f} m<br>Altitude: %{z:.1f} m<br>Speed: %{customdata[1]:.1f} m/s<br>Heading: %{customdata[2]:.1f} deg<br>Pitch: %{customdata[3]:.1f} deg<br>Alive: Yes<extra></extra>'});
const blueCurrent=traces.length;traces.push({type:'scatter3d',mode:'markers+text',name:'Current Blue',x:[],y:[],z:[],text:[],customdata:[],marker:{size:6,color:BLUE},hovertemplate:'%{customdata[0]}<br>Side: Blue<br>Wave: %{customdata[4]}<br>X: %{x:.1f} m<br>Y: %{y:.1f} m<br>Altitude: %{z:.1f} m<br>Speed: %{customdata[1]:.1f} m/s<br>Heading: %{customdata[2]:.1f} deg<br>Pitch: %{customdata[3]:.1f} deg<br>Alive: Yes<extra></extra>'});
const redHead=traces.length;traces.push({type:'scatter3d',mode:'lines',name:'Red headings',x:[],y:[],z:[],line:{color:RED,width:3},showlegend:false});const blueHead=traces.length;traces.push({type:'scatter3d',mode:'lines',name:'Blue headings',x:[],y:[],z:[],line:{color:BLUE,width:3},showlegend:false});
const death=traces.length;traces.push({type:'scatter3d',mode:'markers',name:'Deaths',x:[],y:[],z:[],customdata:[],marker:{symbol:'x',size:8,color:[]},hovertemplate:'%{customdata[0]}<br>%{customdata[1]}<br>Time: %{customdata[2]:.1f} s<br>X: %{x:.1f} m<br>Y: %{y:.1f} m<br>Altitude: %{z:.1f} m<extra></extra>'});
const ang=Array.from({length:100},(_,i)=>2*Math.PI*i/99),arenaTrace=traces.length;traces.push({type:'scatter3d',mode:'lines',name:'Arena',x:ang.map(t=>P.metadata.radius*Math.cos(t)),y:ang.map(t=>P.metadata.radius*Math.sin(t)),z:ang.map(()=>0),line:{color:'#999',width:1}});
const dynamicTraceIndices=[...redTraj,...blueTraj,redCurrent,blueCurrent,redHead,blueHead,death];
const valid=s=>s&&s[0]!==null, deg=x=>x*180/Math.PI, data=(s,label,w)=>[label,s[3],deg(s[5]),deg(s[4]),w||''];
const path=(d,a,b)=>{const q=d.slice(a,b+1).filter(valid);return{x:q.map(s=>s[0]),y:q.map(s=>s[1]),z:q.map(s=>-s[2])}};
const heads=ss=>{const x=[],y=[],z=[];ss.forEach(s=>{if(valid(s)){const L=250,c=Math.cos(s[4]);x.push(s[0],s[0]+L*c*Math.cos(s[5]),null);y.push(s[1],s[1]+L*c*Math.sin(s[5]),null);z.push(-s[2],-s[2]+L*Math.sin(s[4]),null)}});return{x,y,z}};
const eventText=e=>{const i=Math.max(0,Math.min(F-1,Number(e.trace_frame)||0)),p=e.type==='wave_cleared'||e.type==='wave_spawned'?`WAVE ${e.wave||''}`:String(e.type||'').replaceAll('_',' ').toUpperCase();return `${Number(P.time[i]).toFixed(1)} s  ${p}${e.count?` +${e.count}`:''}`};
const result=()=>{const t=String(P.metadata.termination).toLowerCase();if(P.metadata.success||P.waves_cleared[F-1]===P.metadata.total_waves)return'MISSION SUCCESS';if(t.includes('timeout'))return'TIMEOUT';if(t.includes('draw'))return'DRAW';return'RED FAILURE'};
function updatePanels(f,w,now,vd){document.getElementById('slider').value=f;document.getElementById('status').textContent=`${P.metadata.method} | Checkpoint ${P.metadata.checkpoint} | Training seed ${P.metadata.training_seed} | Episode seed ${P.metadata.episode_seed}\nSim time ${now.toFixed(1)} s | Step ${P.steps[f]} | Wave ${P.active_wave[f]} | Waves cleared ${P.waves_cleared[f]} | Red alive ${P.red_alive[f].filter(Boolean).length}/4 | Blue alive ${P.blue_alive[f][w].filter(Boolean).length}/4 | Current Total Blue Losses ${vd.filter(d=>d.side==='blue').length}`;document.getElementById('events').textContent='Recent Events\n'+P.events.filter(e=>e.trace_frame<=f).slice(-5).map(eventText).join('\n');const panel=document.getElementById('result');panel.hidden=f!==F-1;if(!panel.hidden)panel.textContent=`Result: ${result()}\nWaves Cleared ${P.waves_cleared[f]}/${P.metadata.total_waves}\nRed Survivors ${P.red_alive[f].filter(Boolean).length}/4\nTotal Blue Losses ${vd.filter(d=>d.side==='blue').length}\nEpisode Return ${Number(P.metadata.return).toFixed(2)}\nSimulation Time ${now.toFixed(1)} s`}
async function renderFrame(f){const w=Math.max(0,Math.min(P.blue[0].length-1,Number(P.active_wave[f])-1)),now=Number(P.time[f]),choice=document.getElementById('trail').value;let start=0;if(choice!=='full'){while(start<f&&Number(P.time[start])<now-Number(choice))start++}
  const redPaths=redTraj.map((_,a)=>path(P.red.map(r=>r[a]),start,f));
  const bluePaths=blueTraj.map((_,j)=>path(P.blue.map(r=>r[Math.floor(j/4)][j%4]),start,f));
  await Plotly.restyle(plot,{x:redPaths.map(q=>q.x),y:redPaths.map(q=>q.y),z:redPaths.map(q=>q.z),visible:redTraj.map(()=>true)},redTraj);
  await Plotly.restyle(plot,{x:bluePaths.map(q=>q.x),y:bluePaths.map(q=>q.y),z:bluePaths.map(q=>q.z),visible:blueTraj.map(()=>true)},blueTraj);
  const rs=[],bs=[],rx=[],ry=[],rz=[],rt=[],rc=[],bx=[],by=[],bz=[],bt=[],bc=[];for(let a=0;a<4;a++){const s=P.red[f][a];if(P.red_alive[f][a]&&valid(s)){rs.push(s);rx.push(s[0]);ry.push(s[1]);rz.push(-s[2]);rt.push(`R${a+1}`);rc.push(data(s,`R${a+1}`))}}for(let a=0;a<4;a++){const s=P.blue[f][w][a];if(P.blue_alive[f][w][a]&&valid(s)){bs.push(s);bx.push(s[0]);by.push(s[1]);bz.push(-s[2]);bt.push(`B${a+1}`);bc.push(data(s,`B${a+1}`,w+1))}}
  const labels=document.getElementById('labels').checked;await Plotly.restyle(plot,{x:[rx,bx],y:[ry,by],z:[rz,bz],text:[labels?rt:[],labels?bt:[]],customdata:[rc,bc],visible:[true,true]},[redCurrent,blueCurrent]);
  const rh=heads(rs),bh=heads(bs),show=document.getElementById('heads').checked;await Plotly.restyle(plot,{x:[rh.x,bh.x],y:[rh.y,bh.y],z:[rh.z,bh.z],visible:[show,show]},[redHead,blueHead]);
  const vd=P.deaths.filter(d=>d.frame<=f),dc=vd.map(d=>d.side==='red'?RED:BLUE),showDeaths=document.getElementById('markers').checked;await Plotly.restyle(plot,{x:[vd.map(d=>d.position[0])],y:[vd.map(d=>d.position[1])],z:[vd.map(d=>-d.position[2])],customdata:[vd.map(d=>[d.side==='red'?`R${d.agent} death`:`B${d.agent}`,d.wave?`Wave ${d.wave}`:'Red',P.time[Math.min(F-1,d.frame)]])],marker:{color:[dc]},visible:showDeaths},[death]);dynamicHidden=false;updatePanels(f,w,now,vd)
}
async function hideDynamicTraces(){if(!cameraInteracting||dynamicHidden)return;if(renderBusy){hidePending=true;return}renderBusy=true;hidePending=false;try{await Plotly.restyle(plot,{visible:dynamicTraceIndices.map(()=>false)},dynamicTraceIndices);dynamicHidden=true}finally{renderBusy=false;if(!cameraInteracting){renderPending=true;requestRender()}}}
async function drainRenderQueue(){if(renderBusy||cameraInteracting)return;renderBusy=true;try{while(renderPending&&!cameraInteracting){renderPending=false;const target=logicalFrame;await renderFrame(target);renderedFrame=target}}catch(err){console.error('Combat frame render failed',err)}finally{renderBusy=false;if(cameraInteracting&&(hidePending||!dynamicHidden))void hideDynamicTraces();else if(renderPending)void drainRenderQueue()}}
function requestRender(){renderPending=true;if(cameraInteracting||renderBusy)return;void drainRenderQueue()}
function beginCameraInteraction(){if(cameraInteracting)return;cameraInteracting=true;renderPending=true;document.getElementById('camera-interaction').hidden=false;if(renderBusy)hidePending=true;else void hideDynamicTraces()}
function endCameraInteraction(){if(!cameraInteracting)return;cameraInteracting=false;hidePending=false;document.getElementById('camera-interaction').hidden=true;renderPending=true;requestRender()}
function syncLogicalFrame(now=performance.now()){if(!playing)return logicalFrame;const elapsed=Math.max(0,(now-playAnchorWallTime)/1000),steps=Math.floor(elapsed*Number(P.metadata.fps)*speed);logicalFrame=Math.min(F-1,playAnchorFrame+steps*Number(P.metadata.stride));return logicalFrame}
function anchorPlayback(now=performance.now()){playAnchorFrame=logicalFrame;playAnchorWallTime=now}
function pausePlayback(){if(playing)syncLogicalFrame();playing=false;document.getElementById('play').textContent='Play';requestRender()}
function startPlayback(){if(logicalFrame>=F-1)logicalFrame=0;speed=Number(document.getElementById('speed').value);playing=true;anchorPlayback();document.getElementById('play').textContent='Pause';requestRender()}
function seek(frame){pausePlayback();logicalFrame=Math.max(0,Math.min(F-1,Number(frame)));requestRender()}
function playbackLoop(now){if(playing){const previous=logicalFrame;syncLogicalFrame(now);if(logicalFrame!==previous)requestRender();if(logicalFrame>=F-1){playing=false;document.getElementById('play').textContent='Play';requestRender()}}requestAnimationFrame(playbackLoop)}
async function init(){try{if(typeof Plotly==='undefined')throw Error('Plotly failed to initialize.');await Plotly.newPlot(plot,traces,{title:P.metadata.title,uirevision:'combat-replay',scene:{aspectmode:'data',dragmode:'orbit',xaxis:{title:'X / m',range:P.metadata.ranges[0],autorange:false},yaxis:{title:'Y / m',range:P.metadata.ranges[1],autorange:false},zaxis:{title:'Altitude / m',range:P.metadata.ranges[2],autorange:false}},margin:{l:0,r:0,t:40,b:0}},{responsive:true,displaylogo:false,scrollZoom:true});requestRender();document.getElementById('loading').hidden=true;
  document.getElementById('play').onclick=()=>playing?pausePlayback():startPlayback();document.getElementById('slider').oninput=e=>seek(e.target.value);document.getElementById('prev').onclick=()=>seek(logicalFrame-1);document.getElementById('next').onclick=()=>seek(logicalFrame+1);document.getElementById('restart').onclick=()=>seek(0);
  document.getElementById('speed').onchange=e=>{const now=performance.now();if(playing)syncLogicalFrame(now);speed=Number(e.target.value);if(playing)anchorPlayback(now)};['trail','heads','labels','markers'].forEach(id=>document.getElementById(id).onchange=requestRender);document.getElementById('camera').onclick=()=>Plotly.relayout(plot,{'scene.camera':DEFAULT_CAMERA});
  plot.addEventListener('pointerdown',beginCameraInteraction,true);window.addEventListener('pointerup',endCameraInteraction,true);window.addEventListener('pointercancel',endCameraInteraction,true);plot.addEventListener('wheel',()=>{beginCameraInteraction();if(wheelEndTimer!==null)clearTimeout(wheelEndTimer);wheelEndTimer=setTimeout(()=>{wheelEndTimer=null;endCameraInteraction()},200)}, {capture:true,passive:true});requestAnimationFrame(playbackLoop)
}catch(err){console.error(err);document.getElementById('loading').hidden=true;const p=document.getElementById('error-panel');p.hidden=false;p.textContent=`Interactive replay initialization failed\n${err.message}\nCheck browser WebGL support.`}}
init();

