"""Generate a standalone, offline Plotly 3D combat replay."""
from __future__ import annotations
import argparse, json, math, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0, str(ROOT))
from tools.combat_visualization import extract_death_frames, extract_events, infer_method_display_name, read_trace

def _safe(v):
    if isinstance(v, np.ndarray): return [_safe(x) for x in v.tolist()]
    if isinstance(v, (list, tuple)): return [_safe(x) for x in v]
    if isinstance(v, (float, np.floating)) and not math.isfinite(float(v)): return None
    if isinstance(v, np.integer): return int(v)
    if isinstance(v, np.bool_): return bool(v)
    return v

def _ranges(trace, radius):
    alt=[]
    for key in ("red_kinematics", "blue_kinematics"):
        z=-np.asarray(trace[key])[...,2]; alt.extend(z[np.isfinite(z)].tolist())
    maximum=max(0.0, max(alt, default=0.0)); return [[-radius,radius],[-radius,radius],[0.0,math.ceil(maximum+max(200.0,maximum*.05))]]

APP_JS = r"""
const P=JSON.parse(document.getElementById('payload').textContent), plot=document.getElementById('plot'), F=P.time.length;
let frame=0,timer=null; const RED='#d62728',BLUE='#1f77b4',DEFAULT_CAMERA={eye:{x:1.5,y:-1.7,z:1.1},up:{x:0,y:0,z:1}},traces=[];
const redTraj=[],blueTraj=[]; for(let a=0;a<4;a++){redTraj.push(traces.length);traces.push({type:'scatter3d',mode:'lines',name:`Red R${a+1}`,x:[],y:[],z:[],line:{color:RED,width:3}})}
for(let w=0;w<P.blue[0].length;w++)for(let a=0;a<4;a++){blueTraj.push(traces.length);traces.push({type:'scatter3d',mode:'lines',name:`Blue W${w+1} B${a+1}`,x:[],y:[],z:[],line:{color:BLUE,width:2,dash:['solid','dash','dot'][w%3]}})}
const redCurrent=traces.length;traces.push({type:'scatter3d',mode:'markers+text',name:'Current Red',x:[],y:[],z:[],text:[],customdata:[],marker:{size:6,color:RED},hovertemplate:'%{customdata[0]}<br>Side: Red<br>X: %{x:.1f} m<br>Y: %{y:.1f} m<br>Altitude: %{z:.1f} m<br>Speed: %{customdata[1]:.1f} m/s<br>Heading: %{customdata[2]:.1f} deg<br>Pitch: %{customdata[3]:.1f} deg<br>Alive: Yes<extra></extra>'});
const blueCurrent=traces.length;traces.push({type:'scatter3d',mode:'markers+text',name:'Current Blue',x:[],y:[],z:[],text:[],customdata:[],marker:{size:6,color:BLUE},hovertemplate:'%{customdata[0]}<br>Side: Blue<br>Wave: %{customdata[4]}<br>X: %{x:.1f} m<br>Y: %{y:.1f} m<br>Altitude: %{z:.1f} m<br>Speed: %{customdata[1]:.1f} m/s<br>Heading: %{customdata[2]:.1f} deg<br>Pitch: %{customdata[3]:.1f} deg<br>Alive: Yes<extra></extra>'});
const redHead=traces.length;traces.push({type:'scatter3d',mode:'lines',name:'Red headings',x:[],y:[],z:[],line:{color:RED,width:3},showlegend:false});const blueHead=traces.length;traces.push({type:'scatter3d',mode:'lines',name:'Blue headings',x:[],y:[],z:[],line:{color:BLUE,width:3},showlegend:false});
const death=traces.length;traces.push({type:'scatter3d',mode:'markers',name:'Deaths',x:[],y:[],z:[],customdata:[],marker:{symbol:'x',size:8,color:[]},hovertemplate:'%{customdata[0]}<br>%{customdata[1]}<br>Time: %{customdata[2]:.1f} s<br>X: %{x:.1f} m<br>Y: %{y:.1f} m<br>Altitude: %{z:.1f} m<extra></extra>'});
const ang=Array.from({length:100},(_,i)=>2*Math.PI*i/99);traces.push({type:'scatter3d',mode:'lines',name:'Arena',x:ang.map(t=>P.metadata.radius*Math.cos(t)),y:ang.map(t=>P.metadata.radius*Math.sin(t)),z:ang.map(()=>0),line:{color:'#999',width:1}});
const valid=s=>s&&s[0]!==null, deg=x=>x*180/Math.PI, data=(s,label,w)=>[label,s[3],deg(s[5]),deg(s[4]),w||''];
const path=(d,a,b)=>{const q=d.slice(a,b+1).filter(valid);return{x:q.map(s=>s[0]),y:q.map(s=>s[1]),z:q.map(s=>-s[2])}};
const heads=ss=>{const x=[],y=[],z=[];ss.forEach(s=>{if(valid(s)){const L=250,c=Math.cos(s[4]);x.push(s[0],s[0]+L*c*Math.cos(s[5]),null);y.push(s[1],s[1]+L*c*Math.sin(s[5]),null);z.push(-s[2],-s[2]+L*Math.sin(s[4]),null)}});return{x,y,z}};
const eventText=e=>{const i=Math.max(0,Math.min(F-1,Number(e.trace_frame)||0)),p=e.type==='wave_cleared'||e.type==='wave_spawned'?`WAVE ${e.wave||''}`:String(e.type||'').replaceAll('_',' ').toUpperCase();return `${Number(P.time[i]).toFixed(1)} s  ${p}${e.count?` +${e.count}`:''}`};
const result=()=>{const t=String(P.metadata.termination).toLowerCase();if(P.metadata.success||P.waves_cleared[F-1]===P.metadata.total_waves)return'MISSION SUCCESS';if(t.includes('timeout'))return'TIMEOUT';if(t.includes('draw'))return'DRAW';return'RED FAILURE'};
function update(){const f=frame,w=Math.max(0,Math.min(P.blue[0].length-1,Number(P.active_wave[f])-1)),now=Number(P.time[f]),choice=document.getElementById('trail').value;let start=0;if(choice!=='full'){while(start<f&&Number(P.time[start])<now-Number(choice))start++}redTraj.forEach((i,a)=>{const q=path(P.red.map(r=>r[a]),start,f);Plotly.restyle(plot,{x:[q.x],y:[q.y],z:[q.z]},[i])});blueTraj.forEach((i,j)=>{const q=path(P.blue.map(r=>r[Math.floor(j/4)][j%4]),start,f);Plotly.restyle(plot,{x:[q.x],y:[q.y],z:[q.z]},[i])});const rs=[],bs=[],rx=[],ry=[],rz=[],rt=[],rc=[],bx=[],by=[],bz=[],bt=[],bc=[];for(let a=0;a<4;a++){const s=P.red[f][a];if(P.red_alive[f][a]&&valid(s)){rs.push(s);rx.push(s[0]);ry.push(s[1]);rz.push(-s[2]);rt.push(`R${a+1}`);rc.push(data(s,`R${a+1}`))}}for(let a=0;a<4;a++){const s=P.blue[f][w][a];if(P.blue_alive[f][w][a]&&valid(s)){bs.push(s);bx.push(s[0]);by.push(s[1]);bz.push(-s[2]);bt.push(`B${a+1}`);bc.push(data(s,`B${a+1}`,w+1))}}const labels=document.getElementById('labels').checked;Plotly.restyle(plot,{x:[rx],y:[ry],z:[rz],text:[labels?rt:[]],customdata:[rc]},[redCurrent]);Plotly.restyle(plot,{x:[bx],y:[by],z:[bz],text:[labels?bt:[]],customdata:[bc]},[blueCurrent]);const rh=heads(rs),bh=heads(bs),show=document.getElementById('heads').checked;Plotly.restyle(plot,{x:[rh.x],y:[rh.y],z:[rh.z],visible:show},[redHead]);Plotly.restyle(plot,{x:[bh.x],y:[bh.y],z:[bh.z],visible:show},[blueHead]);const vd=P.deaths.filter(d=>d.frame<=f),dc=vd.map(d=>d.side==='red'?RED:BLUE);Plotly.restyle(plot,{x:[vd.map(d=>d.position[0])],y:[vd.map(d=>d.position[1])],z:[vd.map(d=>-d.position[2])],customdata:[vd.map(d=>[d.side==='red'?`R${d.agent} death`:`B${d.agent}`,d.wave?`Wave ${d.wave}`:'Red',P.time[Math.min(F-1,d.frame)]])],marker:{color:[dc]}},[death]);document.getElementById('slider').value=f;document.getElementById('status').textContent=`${P.metadata.method} | Checkpoint ${P.metadata.checkpoint} | Training seed ${P.metadata.training_seed} | Episode seed ${P.metadata.episode_seed}\nSim time ${now.toFixed(1)} s | Step ${P.steps[f]} | Wave ${P.active_wave[f]} | Waves cleared ${P.waves_cleared[f]} | Red alive ${P.red_alive[f].filter(Boolean).length}/4 | Blue alive ${P.blue_alive[f][w].filter(Boolean).length}/4 | Current Total Blue Losses ${vd.filter(d=>d.side==='blue').length}`;document.getElementById('events').textContent='Recent Events\n'+P.events.filter(e=>e.trace_frame<=f).slice(-5).map(eventText).join('\n');const panel=document.getElementById('result');panel.hidden=f!==F-1;if(!panel.hidden)panel.textContent=`Result: ${result()}\nWaves Cleared ${P.waves_cleared[f]}/${P.metadata.total_waves}\nRed Survivors ${P.red_alive[f].filter(Boolean).length}/4\nTotal Blue Losses ${vd.filter(d=>d.side==='blue').length}\nEpisode Return ${Number(P.metadata.return).toFixed(2)}\nSimulation Time ${now.toFixed(1)} s`}
function stop(){if(timer)clearInterval(timer);timer=null;document.getElementById('play').textContent='Play'}function start(){if(frame>=F-1)frame=0;stop();document.getElementById('play').textContent='Pause';timer=setInterval(()=>{if(frame>=F-1){stop();return}frame=Math.min(F-1,frame+P.metadata.stride);update()},1000/(P.metadata.fps*Number(document.getElementById('speed').value)))}
async function init(){try{if(typeof Plotly==='undefined')throw Error('Plotly failed to initialize.');await Plotly.newPlot(plot,traces,{title:P.metadata.title,uirevision:'combat-replay',scene:{aspectmode:'data',xaxis:{title:'X / m',range:P.metadata.ranges[0]},yaxis:{title:'Y / m',range:P.metadata.ranges[1]},zaxis:{title:'Altitude / m',range:P.metadata.ranges[2]}},margin:{l:0,r:0,t:40,b:0}},{responsive:true,displaylogo:false});update();document.getElementById('loading').hidden=true;document.getElementById('play').onclick=()=>timer?stop():start();document.getElementById('slider').oninput=e=>{stop();frame=+e.target.value;update()};document.getElementById('prev').onclick=()=>{stop();frame=Math.max(0,frame-1);update()};document.getElementById('next').onclick=()=>{stop();frame=Math.min(F-1,frame+1);update()};document.getElementById('restart').onclick=()=>{stop();frame=0;update()};document.getElementById('speed').onchange=()=>{if(timer)start()};['trail','heads','labels'].forEach(id=>document.getElementById(id).onchange=update);document.getElementById('markers').onchange=e=>{Plotly.restyle(plot,{visible:e.target.checked},[death]);update()};document.getElementById('camera').onclick=()=>Plotly.relayout(plot,{'scene.camera':DEFAULT_CAMERA})}catch(err){console.error(err);document.getElementById('loading').hidden=true;const p=document.getElementById('error-panel');p.hidden=false;p.textContent=`Interactive replay initialization failed\n${err.message}\nCheck browser WebGL support.`}}
init();
"""

def render(trace_path, metadata_path, output, playback_fps=20, frame_stride=1, initial_trail="full", title="Combat Episode Replay"):
    trace=read_trace(Path(trace_path)); meta=json.loads(Path(metadata_path).read_text(encoding="utf-8"));
    if int(meta.get("trace_schema_version",1))!=1: raise ValueError("unsupported trace schema")
    radius=float(meta.get("arena_radius",5000)); payload={"red":_safe(trace["red_kinematics"]),"red_alive":_safe(trace["red_alive"]),"blue":_safe(trace["blue_kinematics"]),"blue_alive":_safe(trace["blue_alive"]),"steps":_safe(trace["steps"]),"time":_safe(trace["time_s"]),"active_wave":_safe(trace["active_wave"]),"waves_cleared":_safe(trace["waves_cleared"]),"deaths":extract_death_frames(trace),"events":meta.get("events") or extract_events(trace),"metadata":{"method":infer_method_display_name(meta),"checkpoint":meta.get("checkpoint_sampled_steps","?"),"training_seed":meta.get("checkpoint_training_seed","?"),"episode_seed":meta.get("episode_seed","?"),"total_waves":meta.get("total_waves",3),"radius":radius,"ranges":_ranges(trace,radius),"success":bool(meta.get("red_success")),"termination":meta.get("termination_reason",""),"return":meta.get("episode_return",0),"title":title,"fps":float(playback_fps),"stride":max(1,int(frame_stride))}}
    try:
        from plotly.offline import get_plotlyjs; bundle=get_plotlyjs()
    except ImportError as exc: raise RuntimeError("plotly is required for interactive rendering; install plotly>=5.18") from exc
    template=r'''<!doctype html><html><head><meta charset="utf-8"><title>__TITLE__</title><style>body{margin:0;font:14px Arial;color:#222}#bar{padding:8px;background:#f4f6f8;display:flex;gap:6px;align-items:center;flex-wrap:wrap}button,select{padding:5px}#plot{height:calc(100vh - 185px)}#status,#events,#result,#error-panel,#loading{padding:6px 10px;white-space:pre-wrap}#result{background:#eaf5ea;font-weight:bold}#error-panel{background:#fde8e8;color:#a00}label{margin-left:8px}</style></head><body><div id="bar"><button id="play">Play</button><button id="prev">Previous Frame</button><button id="next">Next Frame</button><button id="restart">Restart</button><select id="speed"><option value=".25">0.25x</option><option value=".5">0.5x</option><option value="1" selected>1x</option><option value="2">2x</option><option value="4">4x</option></select><select id="trail"><option value="full">Full trail</option><option value="5">5s trail</option><option value="10">10s trail</option><option value="20">20s trail</option></select><button id="camera">Reset Camera</button><label><input id="heads" type="checkbox" checked> headings</label><label><input id="labels" type="checkbox" checked> labels</label><label><input id="markers" type="checkbox" checked> death markers</label><input id="slider" type="range" min="0" max="__MAX__" value="0" step="1" style="min-width:240px"></div><div id="loading">Loading interactive replay...</div><div id="error-panel" hidden></div><div id="plot"></div><div id="status"></div><div id="events"></div><div id="result" hidden></div><script>__PLOTLY__</script><script type="application/json" id="payload">__PAYLOAD__</script><script id="application-script">// APP_JS_START
__APP_JS__
// APP_JS_END</script></body></html>'''
    html=template.replace("__TITLE__",str(title).replace("&","&amp;").replace('"','&quot;')).replace("__PLOTLY__",bundle).replace("__PAYLOAD__",json.dumps(payload,ensure_ascii=False,separators=(",",":"))).replace("__MAX__",str(len(trace["steps"])-1)).replace("__APP_JS__",APP_JS)
    Path(output).parent.mkdir(parents=True,exist_ok=True);Path(output).write_text(html,encoding="utf-8")

def main():
    p=argparse.ArgumentParser();p.add_argument('--input-dir');p.add_argument('--trace');p.add_argument('--metadata');p.add_argument('--output');p.add_argument('--playback-fps',type=float,default=20);p.add_argument('--frame-stride',type=int,default=1);p.add_argument('--initial-trail',default='full');p.add_argument('--title',default='Combat Episode Replay');a=p.parse_args();d=Path(a.input_dir) if a.input_dir else None;render(Path(a.trace) if a.trace else d/'episode_trace.npz',Path(a.metadata) if a.metadata else d/'metadata.json',Path(a.output) if a.output else d/'episode_interactive.html',a.playback_fps,a.frame_stride,a.initial_trail,a.title)
if __name__=='__main__':main()
